## Reference: https://github.com/helm/chart-testing/blob/main/doc/ct_lint-and-install.md
# Don't add the 'debug' attribute, otherwise the workflow won't work anymore
# Only Used for the CT Install Stage
chart-repos: []
exclude-deprecated: true
excluded-charts:
  - cert-manager
  - cloudflare-tunnel-remote
  - common-library
  - external-dns
  - whoami
github-groups: true
target-branch: main
