apiVersion: v2
name: whoami
description: A Helm Chart for whoami
type: application
version: 0.6.0

maintainers:
  - name: komailo
    url: https://github.com/komailo/helm-charts
sources:
  - https://github.com/komailo/helm-charts
