{{- define "common.external-secret.base" -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .item.name }}
  {{- if .item.namespace }}
  namespace: "{{ .item.namespace }}"
  {{- end }}
spec:
  refreshInterval: "{{ .refreshInterval | default .Values.globals.refreshInterval }}"
  secretStoreRef:
    name: "{{ .secretStoreRefName | default .Values.globals.secretStoreRefName }}"
    kind: "{{ .secretStoreRefKind | default .Values.globals.secretStoreRefKind }}"
  target:
    creationPolicy: Owner
{{- end -}}

{{- define "common.external-secret.overide.simple" -}}
spec:
  target:
    name: "{{ .item.targetName | default .item.name }}"
  data:
    - secretKey: "{{ .item.dataSecretKey }}"
      remoteRef:
        key: "{{ .item.remoteRefKey }}"
{{- end -}}

{{- define "common.external-secret.simple" -}}
{{- $Values := .Values }}
{{- range $index, $item := $Values.SimpleSecrets -}}
{{- $context := dict "item" $item "Values" $Values -}}
{{- with $context }}
---
{{ include "common.utils.merge" (list . "common.external-secret.overide.simple" "common.external-secret.base") }}
{{- end -}}
{{- end -}}
{{- end -}}
