apiVersion: v2
name: common-library
description: A Helm library chart
type: library
version: 0.3.1
maintainers:
  - name: komailo
    url: https://github.com/komailo/helm-charts
sources:
  - https://github.com/komailo/helm-charts
