---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "whoami-{{ .Release.Name }}-http"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "whoami-{{ .Release.Name }}.{{ .Values.externalDnsDomain }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "whoami-{{ .Release.Name }}.{{ .Values.externalDnsDomain }}"
      secretName: whoami-{{ .Release.Name }}-secret
  rules:
    - host: "whoami-{{ .Release.Name }}.{{ .Values.externalDnsDomain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami-{{ .Release.Name }}-svc
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-{{ .Release.Name }}-preview-http
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "whoami-{{ .Release.Name }}-preview.{{ .Values.externalDnsDomain }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "whoami-{{ .Release.Name }}-preview.{{ .Values.externalDnsDomain }}"
      secretName: whoami-{{ .Release.Name }}-preview-secret
  rules:
    - host: "whoami-{{ .Release.Name }}-preview.{{ .Values.externalDnsDomain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami-{{ .Release.Name }}-preview-svc
                port:
                  number: 80
