---
apiVersion: batch/v1
kind: Job
metadata:
  name: whoami-{{ .Release.Name }}-test-external-endpoint
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      name: whoami-{{ .Release.Name }}-test-external-endpoint
    spec:
      containers:
        - name: container-name
          image: curlimages/curl
          command:
            - "curl"
            - --fail-with-body
            - "https://whoami-{{ .Release.Name }}.{{ .Values.externalDnsDomain }}"
      restartPolicy: Never
  backoffLimit: 2
