---
apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
spec:
  type: ClusterIP
  selector:
    app: whoami
  ports:
    - port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: whoami-preview-svc
spec:
  type: ClusterIP
  selector:
    app: whoami
  ports:
    - port: 80
