---
apiVersion: v1
kind: Service
metadata:
  name: whoami-{{ .Release.Name }}-svc
spec:
  type: ClusterIP
  selector:
    app: whoami-{{ .Release.Name }}
  ports:
    - port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: whoami-{{ .Release.Name }}-preview-svc
spec:
  type: ClusterIP
  selector:
    app: whoami-{{ .Release.Name }}
  ports:
    - port: 80
