name: Renovate
on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        id: get_token
        with:
          app-id: ${{ vars.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          submodules: true

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@316d7cd859606d6039a2182b7d69199e9b036835 # v46.2.1
        with:
          configurationFile: .github/configs/renovate.js
          renovate-version: 38.141.1
          token: "${{ steps.get_token.outputs.token }}"
        env:
          LOG_LEVEL: "debug"
          RENOVATE_REPOSITORIES: "${{ github.repository }}"
