{{- range .Values.cluseterIPRange }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .name }}
spec:
  addresses:
  {{- range .range }}
    - {{ . }}
  {{- end }}
  avoidBuggyIPs: true
  autoAssign: {{ .autoAssign | default false }}
{{- end }}
