{{- if .Values.cluseterIPRange }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: host-lan
spec:
  ipAddressPools:
  {{- range .Values.cluseterIPRange }}
    - {{ .name }}
  {{- end }}
{{- end }}
